version: "3.8"

services:
  db:
    image: postgres
    container_name: ss-quiz-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    restart: unless-stopped
    ports:
      - "8001:5432"

  django:
    build:
      context: .
      dockerfile: ./docker/BackendDockerfile
    container_name: ss-quiz-backend
    command: ./docker/backend_setup.sh
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  vue:
    build:
      context: .
      dockerfile: ./docker/FrontendDockerfile
    container_name: ss-quiz-frontend
    ports:
      - "8080:8080"
    depends_on:
      - django